Actio Cable for question answer comments
romka69/qna pull request #8
Opened 2019-03-28 22:06 UTC by romka69

2019-04-02 13:49 UTC, vkurennov requested changes

2019-04-02 13:49 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +            var questionId = $('.question')[0].classList[1].slice(-1);
а если классы поменяют порядок? очень "хрупко" завязываться на порядок классов у элемента. лучше ввести data-атрибут и из него читать id

2019-04-02 13:49 UTC, vkurennov commented on app/assets/javascripts/comment.js
> +            var questionId = $('.question')[0].classList[1].slice(-1);
та же проблема, что и для канала ответов

2019-04-02 13:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +        "answers-#{@answer.question.id}", { answer: @answer, links: links, files: files }
 используй question_id, зачем тянуть из базы ассоциацию (делать лишний запрос), когда у объекта уже и так есть нужные данные?

2019-04-02 13:49 UTC, vkurennov commented on app/controllers/concerns/commented.rb
> +module Commented
А вот это не удачное решение. Гораздо лучше в данном случае было сделать отдельный ресурс комментариев, потому что над комментариями выполняются стандартные CRUD-операции, кроме  того, включая такой консерн в контроллеры вопросов и ответов, нарушается принцип единой отвсетвенности: у тебя контроллеры отвечают за управление вопросами/ответами И комментариями. А "и" в ответсвенности классов быть не должно.

2019-04-02 13:49 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +            partial: 'questions/question',
Не получится рендерить паршалы, т.к. у нас в них есть проверка на current_user, но она будет работать только для юзера, который сделал запрос. А для остальных не будет, ведь ты рассылаешь данные как раз всем юзерам, но сервер не знает (и не может знать) кто из них кто (т.е. не может знать их id и подставить его в current_user, т.к. current_user определяется для каждого запроса по сессии).

2019-04-02 14:17 UTC, romka69 commented on app/controllers/questions_controller.rb
> +            partial: 'questions/question',
В данном паршале нет проверок на пользователя.

2019-04-03 09:46 UTC, vkurennov approved these changes

2019-04-03 09:46 UTC, vkurennov commented on app/controllers/comments_controller.rb
> +  def commentable
Лучше сделать более универсально, например, [так](https://stackoverflow.com/questions/26318815/polymorphic-controller-and-calling-object)

2019-04-03 09:46 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +            partial: 'questions/question',
ок

2019-04-03 10:30 UTC, merged